# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
